# Generated by Django 4.2.4 on 2023-11-07 22:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Telefone', models.IntegerField()),
                ('Mensagem', models.TextField(max_length=500)),
                ('Lido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(upload_to='twitter_img')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_redirecionado', models.URLField()),
                ('short_link', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(max_length=200)),
                ('previa', models.TextField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('por', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', ckeditor.fields.RichTextField(blank=True, max_length=3000, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagens', models.ManyToManyField(blank=True, to='Core.imagemtt')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.url')),
            ],
        ),
    ]
